### ISSUE TITLE
Make visibility classes more automatic

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#110]
The Foundation for Apps visibility classes should mimic the ones in Foundation 5, which affect all breakpoints with a single class. For example, this is the current Apps implementation:

``` scss
.show-for-medium {
  @include breakpoint(medium) {
    display: block !important;
  }
}
```

It should work like this:

``` scss
.show-for-medium {
  display: none !important;

  @include breakpoint(medium) {
    display: block !important;
  }
}
```
