### ISSUE TITLE
Update motion classes to support in/out direction

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#113]
The way the current motion mixins are implemented doesn't account for distinct in/out states. This is because all of the mixins transition to a null position, like so:

``` scss
.slideToRight {
  transform: translateX(-100%);
  &.motion {
    transform: translateX(0%);
  }
}
```

This works for _in_ animations, where you're transitioning _to_ the default state, but doesn't work for _out_ animations, where you're transitioning _away_ from the default state.

To correct this, each transition mixin needs a `$direction` property, which can be set to `in` or `out`. If the direction is out, then the mixin should start at the default state (e.g., `opacity: 1`, `transform: translateX(0)`) and transition to another state when the motion classes are added.
