### ISSUE TITLE
[question] Right to left support

### ISSUE THREAD

**Issue by Nirlah** [zurb/foundation-apps#215]
I saw that in `_global.scss` there is an option to switch to RTL:

``` scss
$text-direction: ltr !default;
$default-float: left !default;
$opposite-direction: right !default;
@if $text-direction == ltr {
  $default-dir: left;
  $opposite-dir: right;
} @else {
  $default-dir: right;
  $opposite-dir: left;
}
```

But in `_settings.scss` there is no option, is there an "easy-switch" to turn foundation for apps to right-to-left like in foundation 5 without hacking the core?

Thanks :smiley:
