### ISSUE TITLE
Problem compiling with gulp-sass

### ISSUE THREAD

**Issue by msuntharesan** [zurb/foundation-apps#288]
Great project by the way. I've been using the web foundation for a long time and we already have planed to use this for next project

Back to the issue
I pulled this through bower foundation-apps. and have my own gulp task to compile the sass
But I am getting this error
stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: Error: Attempted a typeid of NULL pointer!

I narrowed it down to the `@include export` when its not present out this compiles without issue.

my task is 

``` js
 var styles = gulp.src(config.get('paths.styles.app'))
        .pipe($.sourcemaps.init())
        .pipe($.sass())
        .pipe($.sourcemaps.write())
        .pipe(gulp.dest(config.get('dest') + '/css'))
        .on('end', cb);
```

my sass file to test this

``` scss
@import "../bower_components/foundation-apps/scss/helpers/_functions.scss";

@include exports(appGlobal){
    body {
        background-color:#f0f0f0
    }
}
```
