### ISSUE TITLE
Feature request: Unsupported browser detection

### ISSUE THREAD

**Issue by soumak77** [zurb/foundation-apps#484]
I've been using FA in a production environment for a couple months now and I've been getting various issues reported by users for which I was unable to determine root cause.  I've been suspecting a good portion of those issues were due to users trying to use the app on an unsupported browser, however, I hadn't spent the time to really look into it until today.  I finally decided to use Modernizr to perform feature detection in the browser and display a full screen error message overlay in the app if the browser does not support all required features (initially I tried using the notifications in FA to display the error, however, I needed something that was compatible with ANY browser, so I just wrote my own code).

The problem I have is I'm not exactly sure what all features are required by the FA framework.  I ended up just using the flexbox detection, which appears to catch a lot of low hanging fruit, but I'm not sure if there are any browsers that support flexbox that don't support other required features needed by FA.  I could go through the FA codebase and figure out what features are used, however, I suspect that list will evolve over time.  I'm also aware, based on thread discussions, that at some point there is a possibility of FA offering the ability to pick and choose which components to use, in which case the list of features would be dynamic and based on which components are actually chosen, thus a static list is not ideal.  **Is there a way for FA to provide a single API that could be used to determine if the browser can support FA?**

If anyone is aware of a better way to handle notifying the user that their browser is not supported, I'm all ears.  Thanks.

**Comment by gakimball** [comment]
It's definitely something we should address in more detail. The main points of interest are Angular (IE9+ as of Angular 1.3, which we're using) and flexbox (IE10+), but there are lots of little things in the CSS and JS where we get to cut corners because we're only accounting for modern browsers. Like using modern CSS selectors, or DOM features only in newer browsers.

In terms of how to detect it, I think flexbox, like you said, is the most obvious way to check for general compatibility. Flexbox support was our original metric for browser support, so once we knew we were cutting IE9 and Android 2 as a result, we just went from there.

Perhaps we could come up with a small, non-Angular script to drop in a Modernizr-like CSS class to detect lack of support.

And to your point about separate module support, that's possible right now! Our sample bootstrapping code imports every UI plugin at once with the `foundation` module, but that's just a shorthand to import everything at the same time. You can also import each UI component separately, like `foundation.tabs` or `foundation.accordion`.

**Comment by soumak77** [comment]
Good call on the support already existing for FA component selection.  One more thing to add to my backlog.

**Comment by gakimball** [comment]
To come back to this, do you think a CSS class on `<html>` is enough, or would having one of the Foundation services expose an `isCompatible` parameter be more useful? Or both.

**Comment by soumak77** [comment]
An exposed service property would be exactly what I need for my solution (see below).  Since I'm using ng-if, the element will be shown if angular is not supported as the ng-if attribute will have no effect and thus still show the element.  If angular is supported, the result of the expression will be used and since angular is supported, the expression will have access to the exposed service property.

Here's the overlay solution I used (note that Modernizr was added to the scope for this to work):
```html
<div class="browser-not-supported" ng-if="!Modernizr.flexbox">
  <div class="error-message">
    <p>
      We're sorry, but your browser does not support all required functionality needed to run our app.
      Please update your browser by clicking <a href="http://www.browsehappy.com">here</a> or 
      switch to a different device before continuing.  If you're using Internet Explorer, try turning off
      Compatibility View.
    </p>
    <br/>
    <p>
      We apologize for the inconvenience.  If you have any questions, please call us at 
      <a href="tel:+15555555555">555-555-5555</a> or email us at 
      <a href="mailto:test@test.com">test@test.com</a>.
    </p>
  </div>
</div>
```
And here's the accompanying SCSS
```scss
.browser-not-supported {
	.error-message {
		a {
			color: #fff;
			font-weight: bold;
		}
		
		p, a {
			font-family: Arial, Helvetica, sans-serif !important;
		}
	
        background: $alert-color;
        color: #fff;
        padding: 1%;
        width: 50%;
        position: absolute;
        top: 15%;
        left: 50%;
        margin: 0 0 0 -25%; /* add negative left margin for half the width to center the div */
        cursor: default;
        z-index: 10001;
        border-radius: 4px;
        box-shadow: 0 0 5px rgba(0,0,0,0.9);
	}

	position: absolute;
	top: 0;
	left: 0;
	height: 100%; 
	width: 100%; 
	z-index: 10000;
	background: #000; /* fallback */
	background: rgba(0,0,0,0.75);
}
```
