### ISSUE TITLE
Add support for abstract views to routing plugin

### ISSUE THREAD

**Issue by gakimball** [zurb/foundation-apps#495]
Template input:

```yml
name: route
url: /route
abstract: true
```

Result:

```js
$stateProvider.state('route', {
  url: '/route',
  abstract: true
});
```
