### ISSUE TITLE
Add a "debug" mixin

### ISSUE THREAD

**Issue by wldcordeiro** [zurb/foundation-apps#5]
Since this is a very early version of Foundation for Apps I think it would be useful to have a debug mixin similar to the edit mixin available in [Jeet Grid system](http://jeet.gs/) 

Their implementation looks like 

``` scss
@mixin edit() {
  * {
    background: rgba(0, 0, 0, .05);
    filter:progid:DXImageTransform.Microsoft.gradient(startColorstr=#10000000, endColorstr=#10000000);
  }
}
```

But out of personal preference I think naming the mixin debug makes a bit more sense. :)
