### ISSUE TITLE
menu-bar and standalone icons

### ISSUE THREAD

**Issue by dioklecijan** [zurb/foundation-apps#567]
From docs:
*The menu bar supports icons, which can be positioned above, below, to the left, or to the right of the text. Icons can also be used standalone.*

My question is how to align standalone icons? In other words, how to put the icon in the center (horz and vert)?

**Comment by gakimball** [comment]
You can just drop an image into the `<a>` and it will work just fine. There is an issue right now where the image still has a bottom margin, because it's expecting text to be below it. You can fix it for now with this selector:

```css
.menu-bar > li > a > img:first-child:last-child {
  margin: 0;
}
```
