### ISSUE TITLE
Hamburger mixin can’t compile as written

### ISSUE THREAD

**Issue by hguiney** [zurb/foundation-apps#794]
Input:
```scss
  .menu-icon {
    @include hamburger(
      $width: rem-calc( 24 ),
      $left: false,
      $top: false,
      $thickness: rem-calc( 4 ),
      $gap: rem-calc( 3 ),
      $color: #fff,
      $hover-color: darken( #fff, 10% ),
      $offcanvas: false
    );
  }
```

Output:
> Error: Undefined variable: "$opposite-direction".
>         on line 75 of foundation-apps/scss/helpers/_mixins.scss
> \>\> 
>    ------^

If I change it to be `$offcanvas: true`:
> Error: Undefined variable: "$tabbar-menu-icon-width".
>         on line 69 of foundation-apps/scss/helpers/_mixins.scss
> \>\>         left: ($tabbar-menu-icon-width - $width)/2;
>    ---------------^

I have searched both my local directory and this Github repository to see if the variables `$opposite-direction` or `$tabbar-menu-icon-width` are defined anywhere else, and they are not. They both only appear in _mixins.scss.
